name: S3 copy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: ls
      run: |
        echo 'hello 3'
        echo ls -la
